### ISSUE TITLE
New table for accounts 

### ISSUE THREAD

**Issue by sls-lnluksa** [stoivo/JavaSkriptLearn#10]
HAAH!

This is **very** cool
- [x] one
- [x] two

**Comment by sls-lnluksa** [comment]
![academic_icon](https://cloud.githubusercontent.com/assets/6939272/10820900/e55b81f6-7e4f-11e5-87d7-cecf06502606.png)
GOOD
![academic_icon](https://cloud.githubusercontent.com/assets/6939272/10820903/e8dc495a-7e4f-11e5-9355-b55008dbe68e.png)

**Comment by MrdjanStojimirovic** [comment]
Wow Simon this is great!!!

**Comment by mladjo2505** [comment]
:+1:

**Comment by sls-lnluksa** [comment]
I am Nikola

**Comment by sls-lnluksa** [comment]
Work on this 

``` ruby
 rescue Exception => e
      logger.info e.to_s
end
```

**Comment by sls-lnluksa** [comment]
hey
