### ISSUE TITLE
upload images  faster

### ISSUE THREAD

**Issue by sls-lnluksa** [stoivo/JavaSkriptLearn#4]
![d](http://puu.sh/kUvXY/6ea2cf9ef4.png)

**Comment by sls-lnluksa** [comment]
![academic_icon](https://cloud.githubusercontent.com/assets/6939272/10690143/2d1b8ea2-7980-11e5-9cae-65eaad368265.png)

**Comment by stoivo** [comment]
No way this is fixed

**Comment by stoivo** [comment]
This is issue
![matrix](https://cloud.githubusercontent.com/assets/3492040/10753343/b2e7d6a4-7c90-11e5-909e-141bc7aad744.png)
